In [1]:
from liquidation import *

# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_columns', None)

In [2]:
today=Today()
balance=SeasonBalance()

liquidationInvest=LiquidationInvest(balance,today)

In [3]:
liquidationInvest.expectEarn()

                成交       清算價值    預期報酬率
代號   名稱
8429 金麗-KY    9.88  26.526516  249.03%
1337 再生-KY    7.35  15.028928  165.82%
1340 勝悅-KY   12.55  19.767678  104.76%
2609 陽明      42.05  61.729068   90.84%
6405 悅城      24.30  35.551470   90.19%
...            ...        ...      ...
8454 富邦媒    529.00   0.984334  -99.76%
8996 高力     302.50   0.498883  -99.79%
3380 明泰      36.10   0.047190  -99.83%
5285 界霖      78.30   0.024435  -99.96%
2739 寒舍      42.80   0.006328  -99.98%

[1117 rows x 3 columns]