In [1]:
from lynch import *

In [3]:
lynchGrowth(lynchShareBaseDf)

              預期報酬率
代號   名稱
5516 雙喜       55.9%
5508 永信建      29.3%
2371 大同       22.0%
2916 滿心       15.4%
9906 欣巴巴       6.4%
1593 祺驊        0.7%
6873 泓德能源-創   -7.4%
5209 新鼎       -8.5%
6122 擎邦      -15.7%
3032 偉訓      -21.5%
6577 勁豐      -31.2%
3078 僑威      -31.5%
2752 豆府      -32.1%
4754 國碳科     -37.5%
2618 長榮航     -37.8%
3693 營邦      -37.8%
4138 曜亞      -40.9%
5439 高技      -43.4%
2706 第一店     -44.2%
2227 裕日車     -48.6%
2754 亞洲藏壽司   -49.0%
2515 中工      -49.7%
8048 德勝      -49.8%
6472 保瑞      -51.1%
1584 精剛      -51.3%
2707 晶華      -51.9%
2633 台灣高鐵    -52.7%
6703 軒郁      -54.7%
6234 高僑      -56.1%
1796 金穎生技    -62.5%
3540 曜越      -63.7%
2540 愛山林     -66.0%
6291 沛亨      -67.0%
4763 材料-KY   -67.1%
6235 華孚      -71.3%
4979 華星光     -80.4%
3661 世芯-KY   -81.0%
8996 高力      -82.9%
5381 合正      -95.0%

In [4]:
lynchShareDf(lynchShareBaseDf)

                 成交    PER  eps大於0次數  營收年增率超過30%      預期報酬率
代號   名稱
8429 金麗-KY    10.45    NaN       1.0           0        NaN
5907 大洋-KY    14.30    NaN       1.0           0        NaN
2603 長榮      102.00   0.91       4.0           0  15.483516
2929 淘帝-KY    10.90  11.20       1.0           0   0.339286
1340 勝悅-KY    12.45    NaN       0.0           2        NaN
...             ...    ...       ...         ...        ...
6902 走著瞧-創   225.00    NaN       NaN           0        NaN
4944 兆遠        9.96    NaN       0.0           0        NaN
5274 信驊     2470.00  51.20       4.0           0  -0.707031
3529 力旺     1870.00  89.40       4.0           0  -0.832215
3089 億杰         NaN    NaN       NaN           0        NaN

[1790 rows x 5 columns]